---
abstract: 'supply object methods for interacting with GnuPG'
author:
  - 'Frank J. Tobin'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GnuPG-Interface
no_index:
  directory:
    - inc
    - t
    - test
requires:
  Math::BigInt: 1.78
  Moo: 0.091011
  MooX::HandlesVia: 0.001004
  MooX::late: 0.014
resources:
  license: http://dev.perl.org/licenses/
version: 0.47_02
