--- #YAML:1.0
name:               GnuPG-Interface
version:            0.40_02
abstract:           supply object methods for interacting with GnuPG
author:
    - Frank J. Tobin
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:                0.61
    MooseX::AttributeHelpers:  0.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
